### ISSUE TITLE
🐛 BUG: Unexpected token, expected "}" for no reason

### ISSUE THREAD

**Issue by silveltman** [withastro/prettier-plugin-astro#407]
### Describe the Bug

This gives error `Unexpected token, expected "}"`:

```
---
const heading = 'Hello, world!'
const As = 'h1'
---

{
  true && (
    <As>
      {heading}
        <Fragment set:html={'test'} />
    </As>
  )
}

<style>
</style>
```

You can change almost anything in this file and suddenly it works. For example, switch the order or {heading} and Fragment. Or remove the style tag. Or remove the if statement. etc.

These are my deps:
```
  "devDependencies": {
    "prettier": "3.2.5",
    "prettier-plugin-astro": "0.13.0",
    "prettier-plugin-astro-organize-imports": "^0.4.1",
    "prettier-plugin-organize-imports": "^3.2.4"
  }
```

this my prettierconfig:
```
tabWidth: 2
parser: 'typescript'
semi: false
singleQuote: true
trailingComma: 'es5'
singleAttributePerLine: true
svelteStrictMode: false
plugins:
  - 'prettier-plugin-astro'
  - 'prettier-plugin-organize-imports'
  - 'prettier-plugin-astro-organize-imports' # Really must be last

overrides:
  - files: '*.ts'
    options:
      parser: 'typescript'
  - files: '*.astro'
    options:
      parser: 'astro'
```

### Steps to Reproduce

1. npm create astro@latest -- --template minimal
2. add the packages and prettierconfig above in vscode
3. add the code above anywhere, in a page.astro for example
4. look at the prettier output in vscode
